import type { Lesson, PracticeItem } from "@/lib/db/types";

// Conversación track, part 4 — the C1–C2 "mastery" units. This is where a
// learner stops sounding correct and starts sounding NATIVE: diplomatic nuance,
// idioms, professional register, persuasion, abstract discussion, and humor.
// Same chunks-first format; orders continue from 43. A learner who places at
// C1/C2 gets these first, and B2 learners grow into them.

type ChunkRow = { text: string; ipa: string; meaning: string; hint: string };

function chunks(lessonId: string, rows: ChunkRow[]): PracticeItem[] {
  return rows.map((r, i) => ({
    id: `${lessonId}:${i + 1}`,
    text: r.text,
    ipa: r.ipa,
    mouthHint: r.hint,
    kind: "phrase" as const,
    categoryId: "conversation",
    phoneme: "chunk",
    meaning: r.meaning,
  }));
}

export const CONVERSATION_LESSONS_4: Lesson[] = [
  {
    id: "conv-diplomatic",
    title: "Diplomacy & nuance",
    subtitle: "Diplomacia y matices",
    description: "Disagree, hedge, and push back without friction.",
    kind: "phrase",
    categoryIds: ["conversation"],
    track: "conversation",
    order: 44,
    intro: {
      summary: "At C1, the skill isn't being right — it's being right gracefully. Natives disagree constantly, but they cushion it so nobody loses face.",
      whyTricky: "Spanish can sound blunt when translated straight ('No, you're wrong'). English wraps disagreement in softeners ('I hear you, but…', 'I'd push back a little') that keep the room calm.",
      how: ["Cushion first, then differ: 'That's fair, but…'.", "Hedge instead of asserting: 'I'm not entirely convinced'.", "Leave a way out: 'Correct me if I'm wrong'."],
      exampleIds: ["conv-diplomatic:1", "conv-diplomatic:6"],
    },
    items: chunks("conv-diplomatic", [
      { text: "I'd push back on that a little.", ipa: "aɪd pʊʃ bæk ɑn ðæt ə ˈlɪtəl", meaning: "Discreparía un poco de eso.", hint: "'push back' es discrepar con respeto; 'litl' con t suave." },
      { text: "That's fair, but I'd add this.", ipa: "ðæts fɛr bʌt aɪd æd ðɪs", meaning: "Es justo, pero yo agregaría esto.", hint: "Concede con 'that's fair' antes del 'but'." },
      { text: "I'm not entirely convinced.", ipa: "aɪm nɑt ɪnˈtaɪərli kənˈvɪnst", meaning: "No estoy del todo convencida.", hint: "'entirely' = 'entáierli'; suaviza el desacuerdo." },
      { text: "Let's agree to disagree.", ipa: "lɛts əˈɡri tə ˌdɪsəˈɡri", meaning: "Quedemos en que pensamos distinto.", hint: "Frase fija; cierra sin pelear." },
      { text: "With all due respect…", ipa: "wɪð ɔl du rɪˈspɛkt", meaning: "Con todo respeto…", hint: "'due' = 'diu'; señala que viene una objeción cortés." },
      { text: "I hear you, but consider this.", ipa: "aɪ hɪr ju bʌt kənˈsɪdər ðɪs", meaning: "Te entiendo, pero considera esto.", hint: "'I hear you' valida antes de diferir." },
      { text: "That's one way to look at it.", ipa: "ðæts wʌn weɪ tə lʊk æt ɪt", meaning: "Es una forma de verlo.", hint: "Reconoce sin comprometerte del todo." },
      { text: "I'd be careful assuming that.", ipa: "aɪd bi ˈkɛrfəl əˈsumɪŋ ðæt", meaning: "Tendría cuidado con asumir eso.", hint: "'assuming' = 'asúming'; advertencia suave." },
      { text: "Correct me if I'm wrong.", ipa: "kəˈrɛkt mi ɪf aɪm rɔŋ", meaning: "Corrígeme si me equivoco.", hint: "Abre espacio; muy usado antes de opinar." },
      { text: "Let's find some middle ground.", ipa: "lɛts faɪnd sʌm ˈmɪdəl ɡraʊnd", meaning: "Busquemos un punto medio.", hint: "'middle ground' = terreno común." },
    ]),
  },
  {
    id: "conv-idioms",
    title: "Idioms that land",
    subtitle: "Modismos que suenan",
    description: "Everyday American idioms, used the right way.",
    kind: "phrase",
    categoryIds: ["conversation"],
    track: "conversation",
    order: 45,
    intro: {
      summary: "Idioms are the fingerprints of a fluent speaker. A handful, dropped in naturally, make you sound like you live in the language — not like you're reciting it.",
      whyTricky: "You can't translate them word for word ('piece of cake' isn't about cake). Learn each as a whole unit and match it to the right moment.",
      how: ["Memorize each as one block, not word by word.", "Match the situation: 'piece of cake' = easy.", "Don't overuse — one well-placed idiom beats five."],
      exampleIds: ["conv-idioms:1", "conv-idioms:6"],
    },
    items: chunks("conv-idioms", [
      { text: "It's a piece of cake.", ipa: "ɪts ə pis əv keɪk", meaning: "Es pan comido.", hint: "'piece of' = 'pís ov'; significa muy fácil." },
      { text: "Let's cut to the chase.", ipa: "lɛts kʌt tə ðə tʃeɪs", meaning: "Vamos al grano.", hint: "'chase' = 'cheis'; ir directo al punto." },
      { text: "That rings a bell.", ipa: "ðæt rɪŋz ə bɛl", meaning: "Eso me suena.", hint: "'rings a bell' = me resulta familiar." },
      { text: "I'm on the fence about it.", ipa: "aɪm ɑn ðə fɛns əˈbaʊt ɪt", meaning: "Estoy indecisa.", hint: "'on the fence' = sin decidir." },
      { text: "It's not my cup of tea.", ipa: "ɪts nɑt maɪ kʌp əv ti", meaning: "No es lo mío.", hint: "'cup of tea' = gusto personal." },
      { text: "We're on the same page.", ipa: "wɪr ɑn ðə seɪm peɪdʒ", meaning: "Estamos en la misma sintonía.", hint: "'same page' = de acuerdo, alineados." },
      { text: "That's the last straw.", ipa: "ðæts ðə læst strɔ", meaning: "Es la gota que colmó el vaso.", hint: "'straw' = 'stro'; el límite final." },
      { text: "Let's touch base later.", ipa: "lɛts tʌtʃ beɪs ˈleɪtər", meaning: "Nos ponemos al día luego.", hint: "'touch base' = ponerse en contacto." },
      { text: "It cost an arm and a leg.", ipa: "ɪt kɔst ən ɑrm ənd ə lɛɡ", meaning: "Costó un ojo de la cara.", hint: "Idioma fijo; algo carísimo." },
      { text: "I'll take a rain check.", ipa: "aɪl teɪk ə reɪn tʃɛk", meaning: "Lo dejamos para otra ocasión.", hint: "'rain check' = posponer una invitación." },
    ]),
  },
  {
    id: "conv-professional",
    title: "At work, sharp",
    subtitle: "En el trabajo, con soltura",
    description: "Meetings, email-speak, and negotiation register.",
    kind: "phrase",
    categoryIds: ["conversation"],
    track: "conversation",
    order: 46,
    intro: {
      summary: "Professional English has its own register — crisp, a little indirect, full of set phrases. These are the ones that come up in every meeting and thread.",
      whyTricky: "Directness that's normal in Spanish can read as pushy at work; English business-speak softens and packages ('circle back', 'set expectations'). It's a code you learn as chunks.",
      how: ["Use the set phrase natives expect: 'circle back', 'follow up'.", "Soften asks: 'Can you walk me through it?'.", "Signal process: 'let's align on next steps'."],
      exampleIds: ["conv-professional:1", "conv-professional:6"],
    },
    items: chunks("conv-professional", [
      { text: "Let's circle back on that.", ipa: "lɛts ˈsɜrkəl bæk ɑn ðæt", meaning: "Retomamos eso después.", hint: "'circle back' = volver a un tema luego." },
      { text: "Can you walk me through it?", ipa: "kæn ju wɔk mi θru ɪt", meaning: "¿Me lo explicas paso a paso?", hint: "'walk me through' = guiar por los detalles." },
      { text: "I'll follow up by end of day.", ipa: "aɪl ˈfɑloʊ ʌp baɪ ɛnd əv deɪ", meaning: "Te doy seguimiento hoy mismo.", hint: "'end of day' (EOD) = antes de que acabe el día." },
      { text: "Let's align on next steps.", ipa: "lɛts əˈlaɪn ɑn nɛkst stɛps", meaning: "Pongámonos de acuerdo en los siguientes pasos.", hint: "'align' = 'aláin'; coordinar." },
      { text: "That's outside my wheelhouse.", ipa: "ðæts ˌaʊtˈsaɪd maɪ ˈwilhaʊs", meaning: "Eso no es mi área.", hint: "'wheelhouse' = área de dominio." },
      { text: "Let me loop in the team.", ipa: "lɛt mi lup ɪn ðə tim", meaning: "Déjame incluir al equipo.", hint: "'loop in' = sumar a alguien a la conversación." },
      { text: "We're stretched pretty thin.", ipa: "wɪr strɛtʃt ˈprɪti θɪn", meaning: "Estamos con poca capacidad.", hint: "'stretched thin' = sin recursos de sobra." },
      { text: "Let's table this for now.", ipa: "lɛts ˈteɪbəl ðɪs fər naʊ", meaning: "Dejemos esto en pausa por ahora.", hint: "'table it' = aplazar un tema (uso de EE. UU.)." },
      { text: "I want to set expectations.", ipa: "aɪ wɑnt tə sɛt ˌɛkspɛkˈteɪʃənz", meaning: "Quiero dejar claras las expectativas.", hint: "Frase clave para evitar malentendidos." },
      { text: "Let's get the ball rolling.", ipa: "lɛts ɡɛt ðə bɔl ˈroʊlɪŋ", meaning: "Pongámonos en marcha.", hint: "'ball rolling' = arrancar algo." },
    ]),
  },
  {
    id: "conv-persuade",
    title: "Making your case",
    subtitle: "Defender tu punto",
    description: "Persuade, concede, and rebut like a native.",
    kind: "phrase",
    categoryIds: ["conversation"],
    track: "conversation",
    order: 47,
    intro: {
      summary: "C2 is where you can win an argument and keep a friend. Persuasion in English leans on conceding a little to gain a lot — granting a point, then turning it.",
      whyTricky: "The rhythm of debate is idiomatic: you concede ('you've got a point'), pivot ('that said'), and land ('at the end of the day'). These connectors carry the persuasion, not big vocabulary.",
      how: ["Concede, then pivot: 'You've got a point, but…'.", "Frame your view: 'The way I see it…'.", "Land it: 'At the end of the day, it comes down to…'."],
      exampleIds: ["conv-persuade:2", "conv-persuade:6"],
    },
    items: chunks("conv-persuade", [
      { text: "Hear me out on this.", ipa: "hɪr mi aʊt ɑn ðɪs", meaning: "Escúchame hasta el final.", hint: "'hear me out' = déjame terminar mi idea." },
      { text: "The way I see it…", ipa: "ðə weɪ aɪ si ɪt", meaning: "Tal como yo lo veo…", hint: "Introduce tu postura con seguridad." },
      { text: "That said, there's a catch.", ipa: "ðæt sɛd ðɛrz ə kætʃ", meaning: "Dicho esto, hay un pero.", hint: "'that said' pivota; 'catch' = truco/pega." },
      { text: "You've got a point, but consider this.", ipa: "juv ɡɑt ə pɔɪnt bʌt kənˈsɪdər ðɪs", meaning: "Tienes razón, pero considera esto.", hint: "Concede antes de girar el argumento." },
      { text: "Let's play devil's advocate.", ipa: "lɛts pleɪ ˈdɛvəlz ˈædvəkɪt", meaning: "Hagamos de abogado del diablo.", hint: "'devil's advocate' = argumentar el lado opuesto." },
      { text: "At the end of the day, it comes down to trust.", ipa: "ət ði ɛnd əv ðə deɪ ɪt kʌmz daʊn tə trʌst", meaning: "A fin de cuentas, se reduce a la confianza.", hint: "'comes down to' = se reduce a." },
      { text: "I'll grant you that, however…", ipa: "aɪl ɡrænt ju ðæt haʊˈɛvər", meaning: "Te concedo eso, sin embargo…", hint: "'grant you' = admitir un punto." },
      { text: "That's beside the point.", ipa: "ðæts bɪˈsaɪd ðə pɔɪnt", meaning: "Eso no viene al caso.", hint: "'beside the point' = irrelevante." },
      { text: "Let's not lose sight of the goal.", ipa: "lɛts nɑt luz saɪt əv ðə ɡoʊl", meaning: "No perdamos de vista el objetivo.", hint: "'lose sight of' = olvidar lo importante." },
      { text: "If anything, it proves my point.", ipa: "ɪf ˈɛniθɪŋ ɪt pruvz maɪ pɔɪnt", meaning: "Si acaso, prueba lo que digo.", hint: "'if anything' invierte el argumento a tu favor." },
    ]),
  },
  {
    id: "conv-abstract",
    title: "Big ideas",
    subtitle: "Ideas grandes",
    description: "Discuss abstract, complex topics with ease.",
    kind: "phrase",
    categoryIds: ["conversation"],
    track: "conversation",
    order: 48,
    intro: {
      summary: "Real fluency shows up when the topic gets abstract — trade-offs, hypotheticals, nuance. English has ready-made phrases for exactly these moves.",
      whyTricky: "Abstract talk is dense with idiom ('gray area', 'cuts both ways', 'slippery slope'). Each compresses a whole idea; knowing them lets you think out loud at native speed.",
      how: ["Name the nuance: 'it's a bit of a gray area'.", "Signal a hypothesis: 'hypothetically speaking…'.", "Compress the trade-off: 'it cuts both ways'."],
      exampleIds: ["conv-abstract:1", "conv-abstract:6"],
    },
    items: chunks("conv-abstract", [
      { text: "It's a bit of a gray area.", ipa: "ɪts ə bɪt əv ə ɡreɪ ˈɛriə", meaning: "Es una zona gris.", hint: "'gray area' = ni blanco ni negro." },
      { text: "In hindsight, it makes sense.", ipa: "ɪn ˈhaɪndsaɪt ɪt meɪks sɛns", meaning: "Viéndolo en retrospectiva, tiene sentido.", hint: "'hindsight' = 'jáindsait'; mirar atrás." },
      { text: "It's easier said than done.", ipa: "ɪts ˈiziər sɛd ðən dʌn", meaning: "Del dicho al hecho hay mucho trecho.", hint: "Frase fija; decirlo es fácil, hacerlo no." },
      { text: "There's more to it than that.", ipa: "ðɛrz mɔr tu ɪt ðən ðæt", meaning: "Hay más de lo que parece.", hint: "'more to it' = hay más detrás." },
      { text: "It cuts both ways.", ipa: "ɪt kʌts boʊθ weɪz", meaning: "Es un arma de doble filo.", hint: "'cuts both ways' = afecta a ambos lados." },
      { text: "Hypothetically speaking…", ipa: "ˌhaɪpəˈθɛtɪkli ˈspikɪŋ", meaning: "Hipotéticamente hablando…", hint: "Palabra larga; sepárala: 'hai-po-THE-ti-kli' — th con la lengua entre los dientes." },
      { text: "It boils down to trust.", ipa: "ɪt bɔɪlz daʊn tə trʌst", meaning: "Todo se reduce a la confianza.", hint: "'boils down to' = se reduce a lo esencial." },
      { text: "That's a slippery slope.", ipa: "ðæts ə ˈslɪpəri sloʊp", meaning: "Ese es un camino peligroso.", hint: "'slippery slope' = una cosa lleva a otra peor." },
      { text: "It's the exception, not the rule.", ipa: "ɪts ði ɪkˈsɛpʃən nɑt ðə rul", meaning: "Es la excepción, no la regla.", hint: "Contraste fijo; ritmo parejo." },
      { text: "Time will tell.", ipa: "taɪm wɪl tɛl", meaning: "El tiempo lo dirá.", hint: "Cierre corto y natural." },
    ]),
  },
  {
    id: "conv-humor",
    title: "Humor & banter",
    subtitle: "Humor y chispa",
    description: "Sarcasm, teasing, and jokes that land.",
    kind: "phrase",
    categoryIds: ["conversation"],
    track: "conversation",
    order: 49,
    intro: {
      summary: "Humor is the last thing you master in another language — and the first thing that makes people feel you truly belong. American banter runs on sarcasm and gentle teasing.",
      whyTricky: "Tone flips the meaning: 'Yeah, right' means the opposite of yes. Sarcasm lives in delivery, so timing and a flat tone matter as much as the words.",
      how: ["Flatten your tone for sarcasm: 'Yeah, right'.", "Signal a joke: 'I'm just messing with you'.", "Play along: 'Tell me about it'."],
      exampleIds: ["conv-humor:2", "conv-humor:4"],
    },
    items: chunks("conv-humor", [
      { text: "You're killing me.", ipa: "jʊr ˈkɪlɪŋ mi", meaning: "Me matas (de risa).", hint: "Tono divertido; reacción a algo gracioso o exasperante." },
      { text: "Yeah, right.", ipa: "jɛ raɪt", meaning: "Sí, claro (irónico).", hint: "Tono plano = sarcasmo; significa lo contrario." },
      { text: "No pun intended.", ipa: "noʊ pʌn ɪnˈtɛndɪd", meaning: "Sin querer el juego de palabras.", hint: "'pun' = juego de palabras; se dice tras uno sin querer." },
      { text: "I'm just messing with you.", ipa: "aɪm dʒʌst ˈmɛsɪŋ wɪð ju", meaning: "Solo te estoy molestando.", hint: "'messing with you' = bromeando, sin maldad." },
      { text: "That's rich, coming from you.", ipa: "ðæts rɪtʃ ˈkʌmɪŋ frəm ju", meaning: "Mira quién habla.", hint: "'that's rich' = irónico; el otro es el menos indicado." },
      { text: "Don't quit your day job.", ipa: "doʊnt kwɪt jʊr deɪ dʒɑb", meaning: "No dejes tu trabajo (no sirves para eso).", hint: "Broma amistosa sobre algo que alguien hace mal." },
      { text: "Tell me about it.", ipa: "tɛl mi əˈbaʊt ɪt", meaning: "Ni me lo digas.", hint: "No es literal; significa 'te entiendo totalmente'." },
      { text: "You wish!", ipa: "ju wɪʃ", meaning: "¡Ya quisieras!", hint: "Réplica juguetona a algo improbable." },
      { text: "That went over my head.", ipa: "ðæt wɛnt ˈoʊvər maɪ hɛd", meaning: "No lo pillé / se me pasó.", hint: "'over my head' = no lo entendí." },
      { text: "Same old, same old.", ipa: "seɪm oʊld seɪm oʊld", meaning: "Lo de siempre.", hint: "Respuesta casual a '¿cómo va todo?'." },
    ]),
  },
];
