import type { Lesson, PracticeItem } from "@/lib/db/types";

// Conversación track, part 2 — the real-world units that make the curriculum
// comprehensive: numbers, time, family, work, getting around, travel, hotels,
// health, weather, feelings, the phone, and emergencies. Same chunks-first
// format as conversation.ts; every phrase carries its Spanish meaning + a
// Colombian-Spanish pronunciation hint. Orders continue from 28.

type ChunkRow = { text: string; ipa: string; meaning: string; hint: string };

function chunks(lessonId: string, rows: ChunkRow[]): PracticeItem[] {
  return rows.map((r, i) => ({
    id: `${lessonId}:${i + 1}`,
    text: r.text,
    ipa: r.ipa,
    mouthHint: r.hint,
    kind: "phrase" as const,
    categoryId: "conversation",
    phoneme: "chunk",
    meaning: r.meaning,
  }));
}

export const CONVERSATION_LESSONS_2: Lesson[] = [
  {
    id: "conv-numbers",
    title: "Numbers & prices",
    subtitle: "Números y precios",
    description: "Say and understand any price, quantity, or amount.",
    kind: "phrase",
    categoryIds: ["conversation"],
    track: "conversation",
    order: 29,
    intro: {
      summary: "Numbers are everywhere real life happens — prices, phone numbers, times, addresses. A few patterns cover almost all of them.",
      whyTricky: "English 'teen' vs 'ty' (thirteen vs thirty) trips everyone; the stress is the clue. And prices are said as two numbers: 'five ninety-nine', not 'five point ninety-nine'.",
      how: ["Stress the difference: thir-TEEN vs THIR-ty.", "Prices = dollars + cents: '$5.99' → 'five ninety-nine'.", "Ask 'How much?' for anything you want to buy."],
      exampleIds: ["conv-numbers:3", "conv-numbers:6"],
    },
    items: chunks("conv-numbers", [
      { text: "How much is it?", ipa: "/haʊ mʌtʃ ɪz ɪt/", meaning: "¿Cuánto cuesta?", hint: "Se junta: 'jau-MACH-i-sit'. Tu pregunta para comprar todo." },
      { text: "It's five ninety-nine", ipa: "/ɪts faɪv ˈnaɪnti naɪn/", meaning: "Cuesta cinco noventa y nueve", hint: "Los precios se dicen en dos: 'faiv NAIN-ti-nain'." },
      { text: "That's too expensive", ipa: "/ðæts tuː ɪkˈspɛnsɪv/", meaning: "Eso es muy caro", hint: "'too' = demasiado. 'iks-PEN-siv', acento en PEN." },
      { text: "Do you have a discount?", ipa: "/də juː hæv ə ˈdɪskaʊnt/", meaning: "¿Tienen descuento?", hint: "'DIS-kaunt', acento al inicio. 'Do you' débil: 'da-yu'." },
      { text: "I'll take two", ipa: "/aɪl teɪk tuː/", meaning: "Me llevo dos", hint: "'I'll' = 'ail', muy rápido. Para decir cuántos quieres." },
      { text: "What's your phone number?", ipa: "/wʌts jɔːr foʊn ˈnʌmbər/", meaning: "¿Cuál es tu número?", hint: "'NAM-ber' con r americana suave al final." },
      { text: "It costs twenty dollars", ipa: "/ɪt kɔsts ˈtwɛnti ˈdɑːlərz/", meaning: "Cuesta veinte dólares", hint: "'DA-lers'. 'costs' termina en 'sts', no te comas la t." },
      { text: "Can you break a twenty?", ipa: "/kæn juː breɪk ə ˈtwɛnti/", meaning: "¿Tienes cambio de veinte?", hint: "'break' = cambiar un billete grande. 'ke-nyu-BREIK'." },
      { text: "It's half price", ipa: "/ɪts hæf praɪs/", meaning: "Está a mitad de precio", hint: "'half' con f, la l no suena: 'jaf-PRAIS'." },
      { text: "Do you take cash?", ipa: "/də juː teɪk kæʃ/", meaning: "¿Aceptan efectivo?", hint: "'cash' = efectivo. Termina con sh suave: 'kash'." },
    ]),
  },
  {
    id: "conv-time",
    title: "Time, days & dates",
    subtitle: "La hora y los días",
    description: "Tell the time, name the day, and set a moment.",
    kind: "phrase",
    categoryIds: ["conversation"],
    track: "conversation",
    order: 30,
    intro: {
      summary: "Every plan needs a time and a day. These phrases let you set one, ask for one, and never miss it.",
      whyTricky: "English says the hour first, then minutes: 'three thirty', not 'thirty past three' at this level. And 'What time?' ≠ 'When?' — time is the clock, when is the day.",
      how: ["Hour + minutes: 3:30 → 'three thirty'.", "'What time?' for the clock, 'What day?' for the calendar.", "'At' for times, 'on' for days: at 3, on Monday."],
      exampleIds: ["conv-time:1", "conv-time:4"],
    },
    items: chunks("conv-time", [
      { text: "What time is it?", ipa: "/wʌt taɪm ɪz ɪt/", meaning: "¿Qué hora es?", hint: "Se junta: 'wat-TAIM-i-sit'." },
      { text: "It's three thirty", ipa: "/ɪts θriː ˈθɜːrti/", meaning: "Son las tres y media", hint: "Dos TH seguidas: 'zri-ZER-ti'. Hora + minutos." },
      { text: "What day is today?", ipa: "/wʌt deɪ ɪz təˈdeɪ/", meaning: "¿Qué día es hoy?", hint: "'to-DEI', acento al final. 'What day' claro." },
      { text: "See you on Monday", ipa: "/siː juː ɑn ˈmʌndeɪ/", meaning: "Nos vemos el lunes", hint: "'on' para los días. 'MAN-dei', no 'mon-day'." },
      { text: "In the morning", ipa: "/ɪn ðə ˈmɔːrnɪŋ/", meaning: "En la mañana", hint: "'MOR-ning' con r americana. 'in the' débil: 'in-tha'." },
      { text: "Are you free tomorrow?", ipa: "/ɑːr juː friː təˈmɑːroʊ/", meaning: "¿Estás libre mañana?", hint: "'ta-MA-rou', acento en MA. 'Are you' se funde: 'ar-yu'." },
      { text: "It's almost noon", ipa: "/ɪts ˈɔːlmoʊst nuːn/", meaning: "Ya casi es mediodía", hint: "'noon' = mediodía. 'OL-moust', la l suena aquí." },
      { text: "Let's meet at seven", ipa: "/lɛts miːt ət ˈsɛvən/", meaning: "Encontrémonos a las siete", hint: "'at' para la hora. 'lets-MIT-at-SE-ven'." },
      { text: "I'm running late", ipa: "/aɪm ˈrʌnɪŋ leɪt/", meaning: "Voy tarde", hint: "'RA-ning' con r americana. Tu frase para avisar." },
      { text: "Every day", ipa: "/ˈɛvri deɪ/", meaning: "Todos los días", hint: "'EV-ri-dei', dos golpes, no tres." },
    ]),
  },
  {
    id: "conv-family",
    title: "Family & people",
    subtitle: "Familia y personas",
    description: "Talk about the people in your life.",
    kind: "phrase",
    categoryIds: ["conversation"],
    track: "conversation",
    order: 31,
    intro: {
      summary: "People ask about your family fast — it's how conversations get warm. A few sentences let you introduce everyone you love.",
      whyTricky: "English uses possessives a lot: 'my husband', 'her sister'. And 'this is...' introduces a person, not 'he is...' when they're right there.",
      how: ["'This is my...' to introduce someone present.", "'I have...' + number for how many.", "Warm up with 'Do you have kids?' — it's normal small talk."],
      exampleIds: ["conv-family:1", "conv-family:3"],
    },
    items: chunks("conv-family", [
      { text: "This is my husband", ipa: "/ðɪs ɪz maɪ ˈhʌzbənd/", meaning: "Este es mi esposo", hint: "'HAZ-bend'. 'This is' se junta: 'dis-iz'." },
      { text: "I have two kids", ipa: "/aɪ hæv tuː kɪdz/", meaning: "Tengo dos hijos", hint: "'kids' = hijos, casual. Termina en dz." },
      { text: "Do you have any brothers or sisters?", ipa: "/də juː hæv ˈɛni ˈbrʌðərz ɔːr ˈsɪstərz/", meaning: "¿Tienes hermanos?", hint: "'BRA-ders' con TH suave. Pregunta muy común." },
      { text: "My family lives in Colombia", ipa: "/maɪ ˈfæməli lɪvz ɪn kəˈlʌmbiə/", meaning: "Mi familia vive en Colombia", hint: "'FA-mi-li', tres golpes. 'lives' con v." },
      { text: "She's my best friend", ipa: "/ʃiːz maɪ bɛst frɛnd/", meaning: "Es mi mejor amiga", hint: "'She's' = 'shis'. 'friend' termina en 'nd'." },
      { text: "He's a little older than me", ipa: "/hiːz ə ˈlɪtəl ˈoʊldər ðæn miː/", meaning: "Es un poco mayor que yo", hint: "'LI-dl' con t suave. 'than' con TH suave." },
      { text: "We're getting married", ipa: "/wɪr ˈɡɛtɪŋ ˈmɛrid/", meaning: "Nos vamos a casar", hint: "'GE-ding' con t suave. 'MER-id', dos golpes." },
      { text: "My mom lives nearby", ipa: "/maɪ mɑm lɪvz ˈnɪrbaɪ/", meaning: "Mi mamá vive cerca", hint: "'mom' = mamá (EE. UU.). 'NIR-bai'." },
      { text: "How's your family?", ipa: "/haʊz jɔːr ˈfæməli/", meaning: "¿Cómo está tu familia?", hint: "'How's' = 'jaus'. Pregunta cálida para empezar." },
      { text: "I miss them", ipa: "/aɪ mɪs ðɛm/", meaning: "Los extraño", hint: "'them' con TH suave: 'dem'. Corta y sentida." },
    ]),
  },
  {
    id: "conv-work",
    title: "Work & jobs",
    subtitle: "Trabajo",
    description: "Say what you do and talk about work.",
    kind: "phrase",
    categoryIds: ["conversation"],
    track: "conversation",
    order: 32,
    intro: {
      summary: "'What do you do?' is one of the first questions Americans ask. These phrases answer it and keep the work talk going.",
      whyTricky: "'What do you do?' means 'what's your job', not 'what are you doing'. And you say 'I'm a...' + job (with 'a'): 'I'm a teacher', never 'I'm teacher'.",
      how: ["Answer 'What do you do?' with 'I'm a...' + job.", "Don't drop the 'a': 'a nurse', 'an engineer'.", "'I work at...' + place, 'I work as...' + role."],
      exampleIds: ["conv-work:1", "conv-work:2"],
    },
    items: chunks("conv-work", [
      { text: "What do you do?", ipa: "/wʌt də juː duː/", meaning: "¿A qué te dedicas?", hint: "'do you' débil: 'wa-da-ya-DU'. = ¿En qué trabajas?" },
      { text: "I'm a nurse", ipa: "/aɪm ə nɜːrs/", meaning: "Soy enfermera", hint: "No olvides 'a'. 'nurse' con r americana: 'ners'." },
      { text: "I work from home", ipa: "/aɪ wɜːrk frʌm hoʊm/", meaning: "Trabajo desde casa", hint: "'work' con r americana. 'jom' con h soplada." },
      { text: "I have a meeting at ten", ipa: "/aɪ hæv ə ˈmiːtɪŋ ət tɛn/", meaning: "Tengo una reunión a las diez", hint: "'MI-ding' con t suave. 'at' para la hora." },
      { text: "I'm looking for a job", ipa: "/aɪm ˈlʊkɪŋ fɔːr ə dʒɑb/", meaning: "Estoy buscando trabajo", hint: "'LU-king'. 'job' con j vibrante: 'dyob'." },
      { text: "How was your day?", ipa: "/haʊ wʌz jɔːr deɪ/", meaning: "¿Cómo estuvo tu día?", hint: "'jau-was-yor-DEI'. Pregunta de cada tarde." },
      { text: "I'm off today", ipa: "/aɪm ɔːf təˈdeɪ/", meaning: "Hoy tengo el día libre", hint: "'off' = libre del trabajo. 'aim-OF-ta-dei'." },
      { text: "Can you send me the email?", ipa: "/kæn juː sɛnd miː ðə ˈiːmeɪl/", meaning: "¿Me envías el correo?", hint: "'I-meil'. 'send me' se junta: 'sen-mi'." },
      { text: "I'm almost done", ipa: "/aɪm ˈɔːlmoʊst dʌn/", meaning: "Ya casi termino", hint: "'done' = terminado: 'dan'. Útil en el trabajo." },
      { text: "Nice job!", ipa: "/naɪs dʒɑb/", meaning: "¡Buen trabajo!", hint: "Elogio corto. 'nais-DYOB'." },
    ]),
  },
  {
    id: "conv-transport",
    title: "Getting around",
    subtitle: "Transporte",
    description: "Take the bus, a cab, or a rideshare with ease.",
    kind: "phrase",
    categoryIds: ["conversation"],
    track: "conversation",
    order: 33,
    intro: {
      summary: "Cities move on buses, trains, and rideshares. These phrases get you where you're going and back.",
      whyTricky: "American cities use specific words: 'subway' (not metro), 'the bus stop', 'a ride'. And you 'catch' or 'take' transport, never 'coger' translated literally.",
      how: ["'Take' or 'catch' the bus/train — not 'coger'.", "Rideshare talk: 'I'll call an Uber.'", "'How do I get to...?' asks the way anywhere."],
      exampleIds: ["conv-transport:1", "conv-transport:4"],
    },
    items: chunks("conv-transport", [
      { text: "How do I get to the airport?", ipa: "/haʊ də aɪ ɡɛt tə ðə ˈɛrpɔːrt/", meaning: "¿Cómo llego al aeropuerto?", hint: "'ER-port'. 'get to the' se aprieta: 'ge-ta-tha'." },
      { text: "Where's the bus stop?", ipa: "/wɛrz ðə bʌs stɑp/", meaning: "¿Dónde está la parada del bus?", hint: "'Where's' = 'uers'. 'bus stop', dos golpes." },
      { text: "I'll take the subway", ipa: "/aɪl teɪk ðə ˈsʌbweɪ/", meaning: "Tomaré el metro", hint: "'subway' = metro (EE. UU.). 'SAB-uei'." },
      { text: "Can you call me a cab?", ipa: "/kæn juː kɔːl miː ə kæb/", meaning: "¿Me pides un taxi?", hint: "'cab' = taxi. 'call me' se junta: 'kol-mi'." },
      { text: "I'm on my way", ipa: "/aɪm ɑn maɪ weɪ/", meaning: "Voy en camino", hint: "'aim-on-mai-UEI'. Avisa que ya vas." },
      { text: "How long does it take?", ipa: "/haʊ lɔŋ dʌz ɪt teɪk/", meaning: "¿Cuánto se demora?", hint: "'does it' se junta: 'da-zit'. Para cualquier trayecto." },
      { text: "Is this seat taken?", ipa: "/ɪz ðɪs siːt ˈteɪkən/", meaning: "¿Está ocupado este asiento?", hint: "'TEI-ken'. 'this seat' claro." },
      { text: "I missed my bus", ipa: "/aɪ mɪst maɪ bʌs/", meaning: "Perdí el bus", hint: "'missed' termina en 'st': 'mist'." },
      { text: "Turn left here", ipa: "/tɜːrn lɛft hɪr/", meaning: "Gira a la izquierda aquí", hint: "'turn' con r americana. Para dar indicaciones." },
      { text: "It's just around the corner", ipa: "/ɪts dʒʌst əˈraʊnd ðə ˈkɔːrnər/", meaning: "Está a la vuelta", hint: "'KOR-ner' con dos r americanas. Muy cerca." },
    ]),
  },
  {
    id: "conv-travel",
    title: "Travel & the airport",
    subtitle: "Viajes",
    description: "Fly, check in, and cross a border smoothly.",
    kind: "phrase",
    categoryIds: ["conversation"],
    track: "conversation",
    order: 34,
    intro: {
      summary: "Airports run on the same few English questions everywhere. Know them and you'll travel calm, not stressed.",
      whyTricky: "Airport English is polite and fixed — 'I'm here on vacation', 'Just this bag'. Officials ask short questions; short, clear answers work best.",
      how: ["Answer the border question: 'business or vacation?'", "Keep answers short and clear at security.", "'Where is...?' finds any gate, desk, or exit."],
      exampleIds: ["conv-travel:2", "conv-travel:5"],
    },
    items: chunks("conv-travel", [
      { text: "I'd like to check in", ipa: "/aɪd laɪk tə tʃɛk ɪn/", meaning: "Quisiera registrarme", hint: "'check in' = registrarse. 'aid-laik-ta-chek-IN'." },
      { text: "I'm here on vacation", ipa: "/aɪm hɪr ɑn veɪˈkeɪʃən/", meaning: "Vengo de vacaciones", hint: "'vacation' = vacaciones (EE. UU.). 'vei-KEI-shan'." },
      { text: "Just this one bag", ipa: "/dʒʌst ðɪs wʌn bæɡ/", meaning: "Solo esta maleta", hint: "'just' = solo. 'dyast-dis-wan-BAG'." },
      { text: "Where is the gate?", ipa: "/wɛr ɪz ðə ɡeɪt/", meaning: "¿Dónde está la puerta?", hint: "'gate' = puerta de abordaje: 'GEIT'." },
      { text: "My flight is delayed", ipa: "/maɪ flaɪt ɪz dɪˈleɪd/", meaning: "Mi vuelo está retrasado", hint: "'flight' con 'fl'. 'di-LEID', acento al final." },
      { text: "How long is the layover?", ipa: "/haʊ lɔŋ ɪz ðə ˈleɪoʊvər/", meaning: "¿Cuánto dura la escala?", hint: "'layover' = escala. 'LEI-ou-ver'." },
      { text: "I need to catch my flight", ipa: "/aɪ niːd tə kætʃ maɪ flaɪt/", meaning: "Necesito alcanzar mi vuelo", hint: "'catch' = alcanzar. 'nid-ta-KACH'." },
      { text: "Is it a nonstop flight?", ipa: "/ɪz ɪt ə ˈnɑnstɑp flaɪt/", meaning: "¿Es un vuelo directo?", hint: "'nonstop' = directo. 'NAN-stap'." },
      { text: "Can I have a window seat?", ipa: "/kæn aɪ hæv ə ˈwɪndoʊ siːt/", meaning: "¿Me da asiento de ventana?", hint: "'WIN-dou-sit'. Tu llave maestra otra vez." },
      { text: "Have a safe trip!", ipa: "/hæv ə seɪf trɪp/", meaning: "¡Buen viaje!", hint: "Despedida de viajero. 'seif-TRIP'." },
    ]),
  },
  {
    id: "conv-hotel",
    title: "At the hotel",
    subtitle: "En el hotel",
    description: "Check in, ask for what you need, check out.",
    kind: "phrase",
    categoryIds: ["conversation"],
    track: "conversation",
    order: 35,
    intro: {
      summary: "A hotel stay is a short, friendly script. These phrases cover arriving, asking, and leaving.",
      whyTricky: "Hotels are extra polite: 'Could I...?' sounds better than 'Can I...?' here. And 'reservation' is stressed in the middle: re-ser-VA-tion.",
      how: ["'I have a reservation' opens check-in.", "'Could I...?' is the polite hotel ask.", "'What time is checkout?' saves you a fee."],
      exampleIds: ["conv-hotel:1", "conv-hotel:4"],
    },
    items: chunks("conv-hotel", [
      { text: "I have a reservation", ipa: "/aɪ hæv ə ˌrɛzərˈveɪʃən/", meaning: "Tengo una reserva", hint: "'re-zer-VEI-shan', acento en VEI." },
      { text: "Is breakfast included?", ipa: "/ɪz ˈbrɛkfəst ɪnˈkluːdɪd/", meaning: "¿Incluye desayuno?", hint: "'BREK-fast', dos golpes. 'in-KLU-did'." },
      { text: "What's the Wi-Fi password?", ipa: "/wʌts ðə ˈwaɪfaɪ ˈpæswɜːrd/", meaning: "¿Cuál es la clave del wifi?", hint: "'WAI-fai'. 'PAS-uerd' con r americana." },
      { text: "Could I get more towels?", ipa: "/kʊd aɪ ɡɛt mɔːr ˈtaʊəlz/", meaning: "¿Me da más toallas?", hint: "'Could I' = más educado. 'TAU-els'." },
      { text: "The room is too cold", ipa: "/ðə ruːm ɪz tuː koʊld/", meaning: "El cuarto está muy frío", hint: "'too' = demasiado. 'RUM' con r americana." },
      { text: "What time is checkout?", ipa: "/wʌt taɪm ɪz ˈtʃɛkaʊt/", meaning: "¿A qué hora es la salida?", hint: "'checkout' = salida. 'CHEK-aut'." },
      { text: "Can I leave my bags here?", ipa: "/kæn aɪ liːv maɪ bæɡz hɪr/", meaning: "¿Puedo dejar mis maletas aquí?", hint: "'leave' con v larga: 'liv'. Muy útil al salir." },
      { text: "Is there a pool?", ipa: "/ɪz ðɛr ə puːl/", meaning: "¿Hay piscina?", hint: "'Is there' = 'iz-der'. 'pool' con l final." },
      { text: "The AC isn't working", ipa: "/ðə ˌeɪˈsiː ˈɪzənt ˈwɜːrkɪŋ/", meaning: "El aire no funciona", hint: "'AC' = aire (ei-SI). 'isn't' = no está." },
      { text: "Thank you for everything", ipa: "/θæŋk juː fɔːr ˈɛvriθɪŋ/", meaning: "Gracias por todo", hint: "Dos TH: 'zank...EV-ri-zing'. Al despedirte." },
    ]),
  },
  {
    id: "conv-health",
    title: "Health & the doctor",
    subtitle: "Salud",
    description: "Say how you feel and get the help you need.",
    kind: "phrase",
    categoryIds: ["conversation"],
    track: "conversation",
    order: 36,
    intro: {
      summary: "When you don't feel well, you need words fast. These let you explain a symptom and ask for care — anywhere.",
      whyTricky: "English uses 'I have a...' for symptoms ('a headache', 'a fever') and 'It hurts' for pain — not 'me duele' translated. Body parts pair with 'my': 'my throat hurts'.",
      how: ["'I have a...' for a symptom, 'It hurts' for pain.", "'My ___ hurts' names where.", "'I need to see a doctor' asks for care clearly."],
      exampleIds: ["conv-health:1", "conv-health:3"],
    },
    items: chunks("conv-health", [
      { text: "I don't feel well", ipa: "/aɪ doʊnt fiːl wɛl/", meaning: "No me siento bien", hint: "'feel' con l final. 'dont-fil-UEL'." },
      { text: "I have a headache", ipa: "/aɪ hæv ə ˈhɛdeɪk/", meaning: "Me duele la cabeza", hint: "'HED-eik'. En inglés 'tienes' un dolor, no 'te duele'." },
      { text: "My throat hurts", ipa: "/maɪ θroʊt hɜːrts/", meaning: "Me duele la garganta", hint: "'throat' con TH + r: 'zrout'. 'hurts' = duele." },
      { text: "I need to see a doctor", ipa: "/aɪ niːd tə siː ə ˈdɑktər/", meaning: "Necesito ver a un médico", hint: "'DAK-ter' con t + r americana. Frase clave." },
      { text: "I have a fever", ipa: "/aɪ hæv ə ˈfiːvər/", meaning: "Tengo fiebre", hint: "'FI-ver' con v y r americana." },
      { text: "Is there a pharmacy nearby?", ipa: "/ɪz ðɛr ə ˈfɑːrməsi ˈnɪrbaɪ/", meaning: "¿Hay una farmacia cerca?", hint: "'FAR-ma-si'. 'NIR-bai' = cerca." },
      { text: "I'm allergic to nuts", ipa: "/aɪm əˈlɜːrdʒɪk tə nʌts/", meaning: "Soy alérgica a las nueces", hint: "'a-LER-dyik'. Frase que puede salvarte." },
      { text: "Can you help me?", ipa: "/kæn juː hɛlp miː/", meaning: "¿Me puedes ayudar?", hint: "'help me' se junta: 'jelp-mi'. Directa y clara." },
      { text: "It hurts right here", ipa: "/ɪt hɜːrts raɪt hɪr/", meaning: "Me duele justo aquí", hint: "'right here' = justo aquí. Señala mientras lo dices." },
      { text: "I'm feeling better", ipa: "/aɪm ˈfiːlɪŋ ˈbɛtər/", meaning: "Me siento mejor", hint: "'BE-der' con t suave americana." },
    ]),
  },
  {
    id: "conv-weather",
    title: "Weather & small talk",
    subtitle: "El clima",
    description: "The safest conversation starter in English.",
    kind: "phrase",
    categoryIds: ["conversation"],
    track: "conversation",
    order: 37,
    intro: {
      summary: "Americans open with the weather constantly — it's friendly and safe. A few lines keep that chat flowing.",
      whyTricky: "Weather uses 'It's...' for everything ('it's hot', 'it's raining') — no subject to translate. And '-ing' for happening now: 'it's raining', not 'it rains' when you mean right now.",
      how: ["'It's...' + weather word covers most of it.", "'-ing' for right now: 'it's snowing'.", "React with 'I know, right?' to keep it going."],
      exampleIds: ["conv-weather:1", "conv-weather:5"],
    },
    items: chunks("conv-weather", [
      { text: "It's really hot today", ipa: "/ɪts ˈrɪli hɑt təˈdeɪ/", meaning: "Hace mucho calor hoy", hint: "'RI-li'. 'It's' abre casi todo del clima." },
      { text: "It's raining", ipa: "/ɪts ˈreɪnɪŋ/", meaning: "Está lloviendo", hint: "'-ing' = ahora mismo. 'REI-ning'." },
      { text: "It looks like rain", ipa: "/ɪt lʊks laɪk reɪn/", meaning: "Parece que va a llover", hint: "'looks like' = parece. 'luks-laik-REIN'." },
      { text: "It's freezing outside", ipa: "/ɪts ˈfriːzɪŋ ˈaʊtsaɪd/", meaning: "Hace un frío terrible afuera", hint: "'freezing' = heladísimo. 'AUT-said'." },
      { text: "What a beautiful day!", ipa: "/wʌt ə ˈbjuːtɪfəl deɪ/", meaning: "¡Qué día tan lindo!", hint: "'BYU-di-ful' con t suave. Alegra cualquier charla." },
      { text: "Don't forget your umbrella", ipa: "/doʊnt fərˈɡɛt jɔːr ʌmˈbrɛlə/", meaning: "No olvides el paraguas", hint: "'am-BRE-la', acento en BRE." },
      { text: "It's getting colder", ipa: "/ɪts ˈɡɛtɪŋ ˈkoʊldər/", meaning: "Está haciendo más frío", hint: "'GE-ding' con t suave. 'KOL-der'." },
      { text: "The weather is nice", ipa: "/ðə ˈwɛðər ɪz naɪs/", meaning: "El clima está bueno", hint: "'WE-der' con TH suave y r americana." },
      { text: "I love the sunshine", ipa: "/aɪ lʌv ðə ˈsʌnʃaɪn/", meaning: "Me encanta el sol", hint: "'SAN-shain'. 'love' con v." },
      { text: "Stay warm!", ipa: "/steɪ wɔːrm/", meaning: "¡Abrígate!", hint: "'warm' con r americana: 'uorm'. Despedida de invierno." },
    ]),
  },
  {
    id: "conv-feelings",
    title: "Feelings & reactions",
    subtitle: "Emociones",
    description: "React like a native — quick, warm, and real.",
    kind: "phrase",
    categoryIds: ["conversation"],
    track: "conversation",
    order: 38,
    intro: {
      summary: "Sounding fluent is mostly about reacting — small, fast phrases that show you're listening and you care.",
      whyTricky: "English reactions are short and idiomatic: 'I'm so happy for you', 'That's too bad'. Silence feels cold in English, so a quick reaction keeps warmth.",
      how: ["React fast — even one short phrase keeps warmth.", "Match the mood: happy, sorry, excited.", "'That's...' + feeling word is a reliable pattern."],
      exampleIds: ["conv-feelings:1", "conv-feelings:4"],
    },
    items: chunks("conv-feelings", [
      { text: "I'm so happy for you", ipa: "/aɪm soʊ ˈhæpi fɔːr juː/", meaning: "Me alegro mucho por ti", hint: "'HA-pi'. Reacción cálida ante buenas noticias." },
      { text: "That's amazing!", ipa: "/ðæts əˈmeɪzɪŋ/", meaning: "¡Qué maravilla!", hint: "'a-MEI-zing'. TH con voz al inicio." },
      { text: "I'm really sorry", ipa: "/aɪm ˈrɪli ˈsɑːri/", meaning: "Lo siento mucho", hint: "'SA-ri' con r americana. Para consolar." },
      { text: "That's too bad", ipa: "/ðæts tuː bæd/", meaning: "Qué lástima", hint: "'too bad' = qué pena. 'dats-tu-BAD'." },
      { text: "I can't wait", ipa: "/aɪ kænt weɪt/", meaning: "No puedo esperar", hint: "'can't' con t final. Emoción por algo próximo." },
      { text: "I'm nervous", ipa: "/aɪm ˈnɜːrvəs/", meaning: "Estoy nerviosa", hint: "'NER-vas' con r americana y schwa." },
      { text: "Don't worry about it", ipa: "/doʊnt ˈwɜːri əˈbaʊt ɪt/", meaning: "No te preocupes", hint: "'WE-ri'. 'about it' se junta: 'a-BAU-dit'." },
      { text: "That makes me happy", ipa: "/ðæt meɪks miː ˈhæpi/", meaning: "Eso me hace feliz", hint: "'makes me' se junta: 'meiks-mi'." },
      { text: "I'm proud of you", ipa: "/aɪm praʊd ʌv juː/", meaning: "Estoy orgullosa de ti", hint: "'praud' con 'pr'. 'of you' = 'a-vyu'." },
      { text: "You've got this", ipa: "/juːv ɡɑt ðɪs/", meaning: "Tú puedes con esto", hint: "'You've' = 'yuv'. Ánimo antes de un reto." },
    ]),
  },
  {
    id: "conv-phone",
    title: "On the phone",
    subtitle: "Por teléfono",
    description: "Call, text, and handle a bad connection.",
    kind: "phrase",
    categoryIds: ["conversation"],
    track: "conversation",
    order: 39,
    intro: {
      summary: "Phone English has its own little script — answering, asking who's calling, and dealing with a bad line.",
      whyTricky: "Phone phrases are fixed: 'This is Mariana', not 'I am Mariana', when you answer. And 'Can you hear me?' is the universal bad-connection fix.",
      how: ["Answer with 'This is...' + your name.", "'Can you hear me?' fixes a bad line.", "'I'll call you back' buys you time."],
      exampleIds: ["conv-phone:1", "conv-phone:4"],
    },
    items: chunks("conv-phone", [
      { text: "Hi, this is Mariana", ipa: "/haɪ ðɪs ɪz .../", meaning: "Hola, habla Mariana", hint: "Al teléfono se dice 'this is', no 'I am'." },
      { text: "Who's calling?", ipa: "/huːz ˈkɔːlɪŋ/", meaning: "¿Quién habla?", hint: "'Who's' = 'jus'. 'KO-ling'." },
      { text: "Can you hear me?", ipa: "/kæn juː hɪr miː/", meaning: "¿Me escuchas?", hint: "'hear me' se junta: 'jir-mi'. Para la mala señal." },
      { text: "I'll call you back", ipa: "/aɪl kɔːl juː bæk/", meaning: "Te devuelvo la llamada", hint: "'call you' = 'ko-yu'. Te da tiempo." },
      { text: "You're breaking up", ipa: "/jɔːr ˈbreɪkɪŋ ʌp/", meaning: "Se está cortando", hint: "'breaking up' = se corta la llamada. 'BREI-king-ap'." },
      { text: "Can you text me?", ipa: "/kæn juː tɛkst miː/", meaning: "¿Me escribes?", hint: "'text' = mensaje de texto. 'tekst-mi'." },
      { text: "Sorry, wrong number", ipa: "/ˈsɑːri rɔŋ ˈnʌmbər/", meaning: "Perdón, número equivocado", hint: "'wrong' con w muda: 'rong'. 'NAM-ber'." },
      { text: "Let me call you later", ipa: "/lɛt miː kɔːl juː ˈleɪtər/", meaning: "Déjame llamarte después", hint: "'LEI-ter' con t suave." },
      { text: "I missed your call", ipa: "/aɪ mɪst jɔːr kɔːl/", meaning: "Perdí tu llamada", hint: "'missed' termina en 'st': 'mist-yor-KOL'." },
      { text: "Talk to you soon", ipa: "/tɔːk tə juː suːn/", meaning: "Hablamos pronto", hint: "'talk to you' = 'to-ka-yu'. Despedida telefónica." },
    ]),
  },
  {
    id: "conv-emergency",
    title: "Help & emergencies",
    subtitle: "Emergencias",
    description: "The words you hope you never need — but must know.",
    kind: "phrase",
    categoryIds: ["conversation"],
    track: "conversation",
    order: 40,
    intro: {
      summary: "In an emergency there's no time to search for words. These few are worth being automatic — for you and for anyone near you.",
      whyTricky: "Emergency English is loud, short, and direct — politeness drops. 'Call 911' (nine-one-one) is the US number, said digit by digit.",
      how: ["Be direct and loud — drop the politeness.", "'911' is 'nine-one-one', digit by digit.", "'I need help' + what, said clearly, gets action."],
      exampleIds: ["conv-emergency:1", "conv-emergency:3"],
    },
    items: chunks("conv-emergency", [
      { text: "I need help!", ipa: "/aɪ niːd hɛlp/", meaning: "¡Necesito ayuda!", hint: "Fuerte y directa. 'nid-JELP'." },
      { text: "Call 911", ipa: "/kɔːl naɪn wʌn wʌn/", meaning: "Llama al 911", hint: "Se dice dígito por dígito: 'nain-wan-wan'." },
      { text: "It's an emergency", ipa: "/ɪts ən ɪˈmɜːrdʒənsi/", meaning: "Es una emergencia", hint: "'i-MER-yen-si', acento en MER." },
      { text: "Where's the hospital?", ipa: "/wɛrz ðə ˈhɑspɪtəl/", meaning: "¿Dónde está el hospital?", hint: "'HAS-pi-dl' con t suave." },
      { text: "Someone is hurt", ipa: "/ˈsʌmwʌn ɪz hɜːrt/", meaning: "Alguien está herido", hint: "'SAM-wan'. 'hurt' con r americana." },
      { text: "Please hurry", ipa: "/pliːz ˈhɜːri/", meaning: "Por favor, rápido", hint: "'HE-ri' con r americana. Corta y urgente." },
      { text: "I lost my phone", ipa: "/aɪ lɔːst maɪ foʊn/", meaning: "Perdí mi teléfono", hint: "'lost' termina en 'st'. 'foun' con h muda... no, 'f'." },
      { text: "Call the police", ipa: "/kɔːl ðə pəˈliːs/", meaning: "Llama a la policía", hint: "'po-LIS', acento al final." },
      { text: "I'm lost", ipa: "/aɪm lɔːst/", meaning: "Estoy perdida", hint: "Dos palabras que piden ayuda. 'aim-LOST'." },
      { text: "Can you show me on the map?", ipa: "/kæn juː ʃoʊ miː ɑn ðə mæp/", meaning: "¿Me muestras en el mapa?", hint: "'show me' se junta: 'shou-mi'. Para orientarte." },
    ]),
  },
];
