// Spanish glosses for drill words. Sound-lesson items don't author `meaning`
// (they were built to train the ear, not vocabulary), but a learner wants to
// know what she's saying — this map puts a translation under every word.
// Colombian Spanish where regional words differ (carro, computador, banano).
// Minimal-pair homographs get both senses ("bate / murciélago").

export const WORD_ES: Record<string, string> = {
  about: "sobre, acerca de",
  again: "otra vez",
  ahead: "adelante",
  around: "alrededor",
  asked: "preguntó",
  ban: "prohibir",
  banana: "banano",
  base: "base",
  bat: "bate / murciélago",
  beat: "ritmo / vencer",
  behind: "detrás",
  berry: "baya (frutita)",
  better: "mejor",
  bird: "pájaro",
  bit: "poquito",
  boat: "bote",
  both: "ambos, los dos",
  breathe: "respirar",
  called: "llamó",
  car: "carro",
  city: "ciudad",
  clothes: "ropa",
  computer: "computador",
  daughter: "hija",
  decided: "decidió",
  desks: "escritorios",
  eat: "comer",
  facts: "hechos",
  feel: "sentir",
  fill: "llenar",
  films: "películas",
  first: "primero",
  girl: "niña, chica",
  happy: "feliz",
  hard: "duro, difícil",
  hat: "sombrero",
  hello: "hola",
  helped: "ayudó",
  honest: "honesto",
  honor: "honor",
  hour: "hora",
  house: "casa",
  it: "eso, lo",
  jail: "cárcel",
  jam: "mermelada",
  jello: "gelatina",
  jet: "jet, avión",
  joke: "chiste",
  later: "más tarde",
  leave: "salir, irse",
  letter: "carta / letra",
  live: "vivir",
  lived: "vivió",
  months: "meses",
  morning: "mañana",
  mother: "madre",
  needed: "necesitó",
  object: "objeto / objetar",
  party: "fiesta",
  photo: "foto",
  photography: "fotografía",
  played: "jugó",
  present: "regalo / presentar",
  pretty: "bonita",
  problem: "problema",
  record: "disco / grabar",
  school: "escuela",
  seat: "asiento",
  sheep: "oveja",
  ship: "barco",
  sink: "lavaplatos / hundirse",
  sister: "hermana",
  sit: "sentarse",
  spain: "España",
  spanish: "español",
  speak: "hablar",
  special: "especial",
  start: "empezar",
  started: "empezó",
  stop: "parar",
  street: "calle",
  student: "estudiante",
  study: "estudiar",
  supply: "suministro",
  support: "apoyo / apoyar",
  teacher: "profesor(a)",
  texts: "mensajes, textos",
  thank: "agradecer",
  the: "el, la",
  thin: "delgado",
  think: "pensar",
  thirty: "treinta",
  this: "esto, este",
  three: "tres",
  tin: "lata",
  used: "usó",
  van: "camioneta",
  vase: "florero",
  vat: "tanque",
  very: "muy",
  vote: "votar",
  walked: "caminó",
  wanted: "quería",
  watched: "miró, vio",
  water: "agua",
  work: "trabajo, trabajar",
  world: "mundo",
  yale: "Yale (universidad)",
  yam: "ñame",
  yellow: "amarillo",
  yet: "todavía",
  yolk: "yema (del huevo)",
};

/** Translation for a drill item: its authored meaning, else the word map. */
export function meaningFor(text: string, authored?: string): string | undefined {
  return authored ?? WORD_ES[text.trim().toLowerCase()];
}
