// Generate voice audio for every curriculum item via ElevenLabs.
//
//   node scripts/generate-audio.mjs           # generate any missing clips (all voices)
//   node scripts/generate-audio.mjs --force   # regenerate everything
//   node scripts/generate-audio.mjs --voice hope   # only one voice
//
// Voices: Joel (the instructor's cloned voice) is the primary and lives at
// public/audio/<key>.mp3. Supporting voices live at public/audio/v/<slug>/<key>.mp3
// and are used for listening variety (ear training, speed round, the Mix button).
//
// Reads ELEVENLABS_API_KEY from the environment or .env.local. Rewrites
// lib/content/audio-manifest.ts so the app knows which clips exist.

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { ALL_ITEMS } from "../lib/content/lessons.ts";
import { audioKey } from "../lib/speech/audio-key.ts";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const AUDIO_DIR = join(ROOT, "public", "audio");
const MANIFEST = join(ROOT, "lib", "content", "audio-manifest.ts");
const API = "https://api.elevenlabs.io/v1";
const MODEL = "eleven_multilingual_v2";
const FORMAT = "mp3_44100_128";
const CONCURRENCY = 5;
const FORCE = process.argv.includes("--force");
const ONLY_VOICE = process.argv.includes("--voice") ? process.argv[process.argv.indexOf("--voice") + 1] : null;

// The cast. Joel is primary (root dir); the rest are the supporting voices.
const VOICES = [
  { slug: "joel", name: "Joel", id: "OH0RKOa9ViI9M4CAHBcv", primary: true },
  { slug: "mariana", name: "Mariana", id: "OB0Jj6v9DGLLgz8dD57i", primary: false },
  { slug: "hope", name: "Hope", id: "tnSpp4vdxKPjI9w0GnoV", primary: false },
  { slug: "eric", name: "Eric", id: "cjVigY5qzO86Huf0OWal", primary: false },
];

function loadEnv() {
  const env = { ...process.env };
  const file = join(ROOT, ".env.local");
  if (existsSync(file)) {
    for (const line of readFileSync(file, "utf8").split("\n")) {
      const m = line.match(/^\s*([A-Za-z0-9_]+)\s*=\s*(.*)\s*$/);
      if (m && !env[m[1]]) env[m[1]] = m[2].replace(/^["']|["']$/g, "");
    }
  }
  return env;
}

const env = loadEnv();
const API_KEY = env.ELEVENLABS_API_KEY;
if (!API_KEY) {
  console.error("Missing ELEVENLABS_API_KEY (env or .env.local).");
  process.exit(1);
}

async function synth(text, voiceId) {
  const res = await fetch(`${API}/text-to-speech/${voiceId}?output_format=${FORMAT}`, {
    method: "POST",
    headers: { "xi-api-key": API_KEY, "Content-Type": "application/json" },
    body: JSON.stringify({
      text,
      model_id: MODEL,
      voice_settings: { stability: 0.5, similarity_boost: 0.75, style: 0, use_speaker_boost: true },
    }),
  });
  if (!res.ok) {
    let detail = res.statusText;
    try {
      detail = JSON.stringify(await res.json());
    } catch {}
    throw new Error(`${res.status} ${detail}`);
  }
  return Buffer.from(await res.arrayBuffer());
}

// De-dupe items that share an audio key.
const byKey = new Map();
for (const item of ALL_ITEMS) byKey.set(audioKey(item.id), item);
const keys = [...byKey.entries()];

const voices = ONLY_VOICE ? VOICES.filter((v) => v.slug === ONLY_VOICE) : VOICES;
const jobs = [];
for (const voice of voices) {
  const dir = voice.primary ? AUDIO_DIR : join(AUDIO_DIR, "v", voice.slug);
  mkdirSync(dir, { recursive: true });
  for (const [key, item] of keys) jobs.push({ voice, key, item, out: join(dir, `${key}.mp3`) });
}

let done = 0;
let made = 0;
let skipped = 0;
let failed = 0;

async function worker(queue) {
  for (;;) {
    const job = queue.shift();
    if (!job) return;
    if (!FORCE && existsSync(job.out)) {
      skipped++;
    } else {
      try {
        const buf = await synth(job.item.text, job.voice.id);
        writeFileSync(job.out, buf);
        made++;
      } catch (e) {
        failed++;
        console.error(`  x ${job.voice.slug}/${job.item.text}: ${e.message}`);
      }
    }
    done++;
    if (done % 20 === 0 || done === jobs.length) {
      process.stdout.write(`\r  ${done}/${jobs.length} (made ${made}, skipped ${skipped}, failed ${failed})   `);
    }
  }
}

console.log(`Generating audio: ${keys.length} items x ${voices.length} voice(s) -> public/audio/`);
const queue = [...jobs];
await Promise.all(Array.from({ length: CONCURRENCY }, () => worker(queue)));
process.stdout.write("\n");

// Manifest: primary keys that exist + alt voices with FULL coverage only.
const primaryKeys = keys.map(([k]) => k).filter((k) => existsSync(join(AUDIO_DIR, `${k}.mp3`))).sort();
const altVoices = VOICES.filter((v) => !v.primary).filter((v) =>
  keys.every(([k]) => existsSync(join(AUDIO_DIR, "v", v.slug, `${k}.mp3`))),
);

const manifest = `// AUTO-GENERATED by scripts/generate-audio.mjs — do not edit by hand.
// Primary clips (Joel) live at /audio/<key>.mp3; supporting voices at
// /audio/v/<slug>/<key>.mp3. Only alt voices with full coverage are listed.

export const AUDIO_VOICE = "Joel";
export const ALT_VOICES: { slug: string; name: string }[] = [
${altVoices.map((v) => `  { slug: ${JSON.stringify(v.slug)}, name: ${JSON.stringify(v.name)} },`).join("\n")}
];
export const AUDIO_KEYS: string[] = [
${primaryKeys.map((k) => `  ${JSON.stringify(k)},`).join("\n")}
];
`;
writeFileSync(MANIFEST, manifest);
console.log(`Manifest: ${primaryKeys.length} primary keys, alt voices with full coverage: ${altVoices.map((v) => v.slug).join(", ") || "none"}`);
if (failed) {
  console.error(`\n${failed} clip(s) failed — re-run to retry the missing ones.`);
  process.exit(1);
}
console.log("Done.");
