import { audioKey } from "./audio-key";
import { ES_AUDIO_KEYS } from "@/lib/content/es-audio-manifest";

// Spanish meaning clips ("Lisa", warm Spanish-accent voice) — pre-generated by
// scripts/generate-es-audio.mjs. The radio prefers these over SpeechSynthesis:
// studio quality, and playing them through the same <audio> element keeps the
// iOS chained-playback chain intact.

const HAVE = new Set(ES_AUDIO_KEYS);

export function hasEsMeaningClip(itemId: string): boolean {
  return HAVE.has(audioKey(itemId));
}

export function esMeaningUrl(itemId: string): string {
  return `/audio/es/${audioKey(itemId)}.mp3`;
}
